Repository myyrakle/rrdb, pull requests merged in 2024-06, with the labels that each got.

#88 [#84] config 기반 실행 구현
  README.md
  src/command/run.rs
  src/constants.rs
  src/constants/README.md
  src/constants/mod.rs
  src/constants/predule.rs
  src/executor/common.rs
  src/executor/config/global.rs
  src/executor/executor.rs
  src/executor/implements/ddl/alter_database.rs
  src/executor/implements/ddl/alter_table.rs
  src/executor/implements/ddl/create_database.rs
  src/executor/implements/ddl/create_table.rs
  src/executor/implements/ddl/drop_database.rs
  src/executor/implements/ddl/drop_table.rs
  src/executor/implements/dml/insert.rs
  src/executor/implements/dml/scan.rs
  src/executor/implements/other/desc_table.rs
  src/executor/implements/other/show_databases.rs
  src/executor/implements/other/show_tables.rs
  src/executor/util.rs
  src/main.rs
  src/pgwire/connection/connection.rs
  src/server/mod.rs
  src/server/option.rs
  src/server/predule.rs
  src/server/server.rs
  src/utils/mod.rs
  src/utils/path.rs
  src/utils/predule.rs
Labels: feature

#91 [#61] linux systemd 구성
  Cargo.toml
  src/executor/config/global.rs
  src/executor/executor.rs
  src/executor/implements/ddl/create_database.rs
  src/executor/initializer.rs
  src/executor/mod.rs
  src/main.rs
Labels: feature

#92 [#90] clippy fix
  src/ast/mod.rs
  src/errors/execute_error.rs
  src/errors/into_error.rs
  src/errors/lexing_error.rs
  src/errors/parsing_error.rs
  src/errors/type_error.rs
  src/executor/common.rs
  src/executor/executor.rs
  src/executor/implements/ddl/alter_database.rs
  src/executor/implements/ddl/alter_table.rs
  src/executor/implements/ddl/create_database.rs
  src/executor/implements/ddl/create_table.rs
  src/executor/implements/ddl/drop_database.rs
  src/executor/implements/ddl/drop_table.rs
  src/executor/implements/dml/delete.rs
  src/executor/implements/dml/insert.rs
  src/executor/implements/dml/scan.rs
  src/executor/implements/dml/select.rs
  src/executor/implements/dml/update.rs
  src/executor/implements/other/desc_table.rs
  src/executor/implements/other/show_databases.rs
  src/executor/implements/other/show_tables.rs
  src/executor/initializer.rs
  src/executor/reduce.rs
  src/lexer/operator_token.rs
  src/lexer/tokenizer.rs
  src/lexer/tokens.rs
  src/parser/implements/common.rs
  src/parser/implements/ddl/database.rs
  src/parser/implements/ddl/table.rs
  src/parser/implements/ddl/top_level.rs
  src/parser/implements/dml/delete.rs
  src/parser/implements/dml/expression.rs
  src/parser/implements/dml/insert.rs
  src/parser/implements/dml/select.rs
  src/parser/implements/dml/update.rs
  src/parser/implements/other/backslash_command.rs
  src/parser/implements/other/desc.rs
  src/parser/implements/other/show.rs
  src/parser/implements/other/use.rs
  src/parser/implements/tcl/begin.rs
  src/parser/test/select.rs
  src/pgwire/connection/connection.rs
  src/pgwire/engine/rrdb.rs
  src/pgwire/protocol/connection_codec.rs
  src/server/server.rs
  src/utils/collection.rs
Labels: refactoring

#94 [#93] MacOS에 대한 DEFAULT_CONFIG_BASEPATH 구성
  src/constants.rs
Labels: enhancement

#95 [#79] MacOS 환경에서의 launchd 데몬 구성
  README.md
  src/constants.rs
  src/executor/initializer.rs
Labels: enhancement

#105 [#101] Default Port를 22208로 변경
  README.md
  src/executor/config/global.rs
Labels: bug
